spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev     #开发环境
  application: 
    name: springcloud-config-fpz-dev
---
spring:
  profiles: test   #测试环境
  application: 
    name: springcloud-config-fpz-test1111
#  请保存为UTF-8格式
 